#!/usr/bin/env python3
"""Generate OpenSCAD Savonius model and blade template DXF from config.json."""

from __future__ import annotations

import json
import math
from pathlib import Path


def load_config(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def blade_length_estimate(height_mm: float, twist_deg: float, radius_mm: float) -> float:
    twist_rad = math.radians(twist_deg)
    circumferential = radius_mm * twist_rad
    return math.sqrt(height_mm**2 + circumferential**2)


def generate_scad(cfg: dict) -> str:
    diameter = float(cfg["diameter_mm"])
    height = float(cfg["height_mm"])
    blade_count = int(cfg.get("blade_count", 2))
    twist = float(cfg["twist_deg"])
    shaft_hole_d = float(cfg["shaft_hole_diameter_mm"])
    plate_t = float(cfg["plate_thickness_mm"])
    plate_margin = float(cfg["plate_margin_mm"])
    blade_t = float(cfg["blade_thickness_mm"])
    slot_clearance = float(cfg["slot_clearance_mm"])
    slot_depth = float(cfg["slot_depth_mm"])
    overlap_ratio = float(cfg["center_overlap_ratio"])

    rotor_r = diameter / 2.0
    half_blade_r = rotor_r / 2.0
    overlap = rotor_r * overlap_ratio
    slot_w = blade_t + slot_clearance
    center_offset = half_blade_r - overlap / 2.0
    plate_r = rotor_r + plate_margin

    return f"""// Auto-generated by generate_savonius_scad.py
// Parametric Savonius rotor

$fn = 96;

diameter_mm = {diameter};
height_mm = {height};
blade_count = {blade_count};
twist_deg = {twist};
shaft_hole_diameter_mm = {shaft_hole_d};
plate_thickness_mm = {plate_t};
plate_margin_mm = {plate_margin};
blade_thickness_mm = {blade_t};
slot_clearance_mm = {slot_clearance};
slot_depth_mm = {slot_depth};
center_overlap_ratio = {overlap_ratio};

rotor_r = diameter_mm/2;
half_blade_r = rotor_r/2;
overlap = rotor_r*center_overlap_ratio;
center_offset = half_blade_r - overlap/2;
plate_r = rotor_r + plate_margin_mm;
slot_w = blade_thickness_mm + slot_clearance_mm;

module blade_shell(sign=1) {{
    rotate([0,0, sign * twist_deg/2])
    linear_extrude(height=height_mm, twist=sign*twist_deg, slices=100)
    translate([sign * center_offset, 0, 0])
    difference() {{
        circle(r=half_blade_r);
        if (sign > 0)
            translate([-half_blade_r, -half_blade_r]) square([half_blade_r, 2*half_blade_r]);
        else
            translate([0, -half_blade_r]) square([half_blade_r, 2*half_blade_r]);
    }}
}}

module end_plate(zpos=0) {{
    translate([0,0,zpos])
    difference() {{
        cylinder(h=plate_thickness_mm, r=plate_r);
        translate([0,0,-0.1]) cylinder(h=plate_thickness_mm+0.2, d=shaft_hole_diameter_mm);

        for (a=[0:360/blade_count:359]) {{
            rotate([0,0,a]) {{
                translate([ center_offset, -slot_w/2, -0.1]) cube([slot_depth_mm, slot_w, plate_thickness_mm+0.2]);
                translate([-center_offset-slot_depth_mm, -slot_w/2, -0.1]) cube([slot_depth_mm, slot_w, plate_thickness_mm+0.2]);
            }}
        }}
    }}
}}

module savonius_rotor() {{
    union() {{
        end_plate(0);
        end_plate(height_mm - plate_thickness_mm);
        blade_shell(1);
        blade_shell(-1);
    }}
}}

savonius_rotor();
"""


def write_blade_template_dxf(cfg: dict, out_path: Path) -> None:
    width = float(cfg.get("blade_width_mm", cfg["diameter_mm"] / 2.0))
    height = float(cfg["height_mm"])
    twist = float(cfg["twist_deg"])
    r = float(cfg["diameter_mm"]) / 4.0
    length = blade_length_estimate(height, twist, r)
    end_r = width / 2.0
    hole_d = float(cfg.get("blade_mount_hole_diameter_mm", 3.2))
    hole_off = float(cfg.get("blade_mount_hole_offset_mm", 15.0))

    cx1 = end_r
    cx2 = length - end_r
    cy = end_r

    dxf = []
    def add(*vals: str) -> None:
        dxf.extend(vals)

    add("0", "SECTION", "2", "HEADER", "0", "ENDSEC")
    add("0", "SECTION", "2", "ENTITIES")

    add("0","LINE","8","0","10",f"{cx1}","20",f"{0}","11",f"{cx2}","21",f"{0}")
    add("0","LINE","8","0","10",f"{cx1}","20",f"{width}","11",f"{cx2}","21",f"{width}")
    add("0","ARC","8","0","10",f"{cx1}","20",f"{cy}","40",f"{end_r}","50","90","51","270")
    add("0","ARC","8","0","10",f"{cx2}","20",f"{cy}","40",f"{end_r}","50","-90","51","90")

    for x in (hole_off, length - hole_off):
        add("0","CIRCLE","8","0","10",f"{x}","20",f"{width/2}","40",f"{hole_d/2}")

    add("0", "ENDSEC", "0", "EOF")
    out_path.write_text("\n".join(dxf) + "\n", encoding="ascii")


def main() -> int:
    cfg_path = Path("config.json")
    if not cfg_path.exists():
        raise SystemExit("config.json not found")

    cfg = load_config(cfg_path)
    out_dir = Path(cfg.get("output_dir", "output"))
    out_dir.mkdir(parents=True, exist_ok=True)

    scad_text = generate_scad(cfg)
    scad_root = Path("savonius.scad")
    scad_out = out_dir / "savonius.scad"
    scad_root.write_text(scad_text, encoding="utf-8")
    scad_out.write_text(scad_text, encoding="utf-8")

    write_blade_template_dxf(cfg, Path("blade_template.dxf"))
    write_blade_template_dxf(cfg, out_dir / "blade_template.dxf")

    print(f"Generated: {scad_root}, {scad_out}, blade_template.dxf")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
